# Library Imports

In [ ]:
!pip install neuralforecast hyperopt

# Data prep & all of them
!pip install utilsforecast
import pandas as pd
import matplotlib.pyplot as plt
from utilsforecast.plotting import plot_series
from utilsforecast.losses import bias, rmse, mae, mape, bias
from utilsforecast.evaluation import evaluate


from neuralforecast import NeuralForecast
from ray import tune
from neuralforecast.auto import AutoNBEATS

Requirement already satisfied: neuralforecast in /usr/local/lib/python3.12/dist-packages (3.1.7)
Requirement already satisfied: hyperopt in /usr/local/lib/python3.12/dist-packages (0.2.7)
Requirement already satisfied: coreforecast>=0.0.6 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (0.0.17)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2025.3.0)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.0.2)
Requirement already satisfied: pandas>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (1.16.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.10.0+cpu)
Requirement already satisfied: tornado>=6.5.5 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (6.5.5)
Requirement already satisfied: pytorch-lightning>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.6.1)
Requirement already satisfied: ray>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (2.55.1)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (4.8.0)
Requirement already satisfied: utilsforecast>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (0.2.16)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from hyperopt) (1.17.0)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.12/dist-packages (from hyperopt) (3.6.1)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from hyperopt) (4.67.3)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from hyperopt) (3.1.2)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt) (0.10.9.9)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->neuralforecast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->neuralforecast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->neuralforecast) (2026.1)
Requirement already satisfied: PyYAML>5.4 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (6.0.3)
Requirement already satisfied: torchmetrics>0.7.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (1.9.0)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (26.1)
Requirement already satisfied: typing-extensions>4.5.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (4.15.0)
Requirement already satisfied: lightning-utilities>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (0.15.3)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (8.3.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.29.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (4.26.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (1.1.2)
Requirement already satisfied: protobuf>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (5.29.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2.32.4)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (2.12.3)
Requirement already satisfied: tensorboardX>=1.9 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (2.6.5)
Requirement already satisfied: pyarrow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (18.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (3.1.6)
Requirement already satisfied: narwhals>=2.0 in /usr/local/lib/python3.12/dist-packages (from utilsforecast>=0.2.3->neuralforecast) (2.20.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->neuralforecast) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->neuralforecast) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->neuralforecast) (2.0.49)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->neuralforecast) (1.3.11)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (3.13.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (0.4.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->neuralforecast) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->neuralforecast) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->neuralforecast) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (0.30.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2026.4.22)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (1.23.0)
Requirement already satisfied: utilsforecast in /usr/local/lib/python3.12/dist-packages (0.2.16)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (26.1)
Requirement already satisfied: pandas<3.0.0 in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (2.2.2)
Requirement already satisfied: narwhals>=2.0 in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (2.20.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0->utilsforecast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0->utilsforecast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0->utilsforecast) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0->utilsforecast) (1.17.0)

# Data Preparation (this is shortened from first version)

In [ ]:
df_base = pd.read_parquet('/content/sample_hotels-1.parquet')
df_base.head()

,unique_id,ds,holiday_flag,target_day,target_month,target_year,location_type,hotel_type,y,otb_1,...,otb_51,otb_52,otb_53,otb_54,otb_55,otb_56,otb_57,otb_58,otb_59,otb_60
1430,hotel_0,2022-01-01,no,Sat,Jan,2022,NonSuburban,Resorts & Destinations,0.975309,0.679012,...,0.197531,0.197531,0.197531,0.185185,0.160494,0.160494,0.160494,0.160494,0.160494,0.160494
1431,hotel_0,2022-01-02,no,Sun,Jan,2022,NonSuburban,Resorts & Destinations,0.493827,0.308642,...,0.074074,0.074074,0.074074,0.074074,0.074074,0.061728,0.061728,0.061728,0.061728,0.049383
1432,hotel_0,2022-01-03,no,Mon,Jan,2022,NonSuburban,Resorts & Destinations,0.456790,0.358025,...,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691
1433,hotel_0,2022-01-04,no,Tue,Jan,2022,NonSuburban,Resorts & Destinations,0.592593,0.419753,...,0.074074,0.074074,0.074074,0.074074,0.061728,0.061728,0.037037,0.037037,0.024691,0.024691
1434,hotel_0,2022-01-05,no,Wed,Jan,2022,NonSuburban,Resorts & Destinations,0.530864,0.407407,...,0.074074,0.074074,0.074074,0.074074,0.074074,0.049383,0.049383,0.024691,0.024691,0.012346

Drop unimformative variable

In [ ]:
df_base = df_base.drop(columns=['target_year'])

Dummies

In [ ]:
 # Convert holiday flag to boolean manually
 df_base['holiday_flag'] = df_base['holiday_flag'].astype('bool')

In [ ]:
cat_cols = [
    'target_day',
    'target_month',
    'location_type',
    'hotel_type'
]

for col in cat_cols:
    df_base[col] = df_base[col].astype('category')

In [ ]:
df_base = pd.get_dummies(df_base, columns=cat_cols, drop_first=True)

OTB

In [ ]:
# Drop all OTB values before otb_28 because that information wouldn't actually be available at the time of forecasting
# By only keeping otb_28 and beyond, I ensure the model doesn't "cheat" by looking at data from inside the 28-day period
columns_to_drop = [f'otb_{i}' for i in range(1, 28)]
df_base = df_base.drop(columns=columns_to_drop)
display(df_base.head())

,unique_id,ds,y,otb_28,otb_29,otb_30,otb_31,otb_32,otb_33,otb_34,...,target_month_Jun,target_month_Mar,target_month_May,target_month_Nov,target_month_Oct,target_month_Sep,location_type_NonSuburban,hotel_type_Key Central Business District,hotel_type_Other High Leisure Mix,hotel_type_Resorts & Destinations
1430,hotel_0,2022-01-01,0.975309,0.296296,0.283951,0.296296,0.296296,0.283951,0.259259,0.234568,...,False,False,False,False,False,False,True,False,False,True
1431,hotel_0,2022-01-02,0.493827,0.086420,0.086420,0.086420,0.086420,0.086420,0.086420,0.086420,...,False,False,False,False,False,False,True,False,False,True
1432,hotel_0,2022-01-03,0.456790,0.061728,0.061728,0.061728,0.061728,0.061728,0.061728,0.049383,...,False,False,False,False,False,False,True,False,False,True
1433,hotel_0,2022-01-04,0.592593,0.111111,0.111111,0.111111,0.111111,0.098765,0.098765,0.098765,...,False,False,False,False,False,False,True,False,False,True
1434,hotel_0,2022-01-05,0.530864,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,...,False,False,False,False,False,False,True,False,False,True

Drop Hotels

In [ ]:
hotels_to_drop = ['hotel_28', 'hotel_77']
df_base = df_base[df_base['unique_id'].isin(hotels_to_drop) == False]

Test/Train and Pred/No Pred Split

In [ ]:
# cutoff
cutoff = '2023-05-31'

#train/test split
train = df_base[df_base['ds'] <= cutoff]
test = df_base[df_base['ds'] > cutoff]

# full df no pred
df_no_pred = df_base[['unique_id', 'ds', 'y']]

# train
train_base = train[['unique_id', 'ds', 'y']] # Nixtila format dataset
train_ml = train.copy() # full dataset for ML

test_base = test[['unique_id', 'ds', 'y']]
test_ml = test.copy()

# AutoNBEATS Cross Validation and Evaluation

In [ ]:
# Extract the default hyperparameter settings for AutoNBEATS
nbeats_config = AutoNBEATS.get_default_config(h=28, backend="ray")

# Customize max_steps (100 for now, 1000 for final)
nbeats_config["max_steps"] = tune.choice([100])

# Using a range for the random seed during the search phase
nbeats_config["random_seed"] = tune.randint(1, 10)

In [ ]:
# Define model
auto_nb_model = [
    AutoNBEATS(
        h=28,
        config=nbeats_config,
        num_samples = 20
    )
]

In [ ]:
# Create model object
n_beat = NeuralForecast(
    models=auto_nb_model,
    freq='D')

In [ ]:
# Cross Validation
cross_autonb = n_beat.cross_validation(
    df = df_base,
    step_size = 28,
    n_windows = 5
)

2026-05-05 12:39:30,402	INFO worker.py:2012 -- Started a local Ray instance.
/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py:2051: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
2026-05-05 12:39:35,618	INFO tune.py:253 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.

+--------------------------------------------------------------------+
| Configuration for experiment     _train_tune_2026-05-05_12-39-18   |
+--------------------------------------------------------------------+
| Search algorithm                 BasicVariantGenerator             |
| Scheduler                        FIFOScheduler                     |
| Number of trials                 20                                |
+--------------------------------------------------------------------+

View detailed results here: /root/ray_results/_train_tune_2026-05-05_12-39-18
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2026-05-05_12-39-18_962880_3837/artifacts/2026-05-05_12-39-35/_train_tune_2026-05-05_12-39-18/driver_artifacts`

(_train_tune pid=4546) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=4546) Seed set to 2
(_train_tune pid=4546) GPU available: False, used: False
(_train_tune pid=4546) TPU available: False, using: 0 TPU cores
(_train_tune pid=4546) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=4546) 2026-05-05 12:39:53.510685: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=4546) 2026-05-05 12:39:53.591433: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=4546) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=4546) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=4546) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=4546) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=4546) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=4546) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=4546) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=4546) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=4546) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=4546) Trainable params: 2.7 M
(_train_tune pid=4546) Non-trainable params: 9.6 K
(_train_tune pid=4546) Total params: 2.7 M
(_train_tune pid=4546) Total estimated model params size (MB): 10
(_train_tune pid=4546) Modules in train mode: 31
(_train_tune pid=4546) Modules in eval mode: 0
(_train_tune pid=4546) Total FLOPs: 0

(_train_tune pid=4546) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=4546) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=4546) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=4546)                                                               train_loss_step:
(_train_tune pid=4546)                                                               0.048
(_train_tune pid=4546)                                                               train_loss_epoch:
(_train_tune pid=4546)                                                               0.048 valid_loss:
(_train_tune pid=4546)                                                               0.186

(_train_tune pid=4727) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=4727) Seed set to 8
(_train_tune pid=4727) GPU available: False, used: False
(_train_tune pid=4727) TPU available: False, using: 0 TPU cores
(_train_tune pid=4727) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=4727) 2026-05-05 12:40:22.550684: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=4727) 2026-05-05 12:40:22.629500: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=4727) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=4727) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=4727) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=4727) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=4727) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=4727) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=4727) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=4727) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=4727) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=4727) Trainable params: 2.6 M
(_train_tune pid=4727) Non-trainable params: 4.8 K
(_train_tune pid=4727) Total params: 2.6 M
(_train_tune pid=4727) Total estimated model params size (MB): 10
(_train_tune pid=4727) Modules in train mode: 31
(_train_tune pid=4727) Modules in eval mode: 0
(_train_tune pid=4727) Total FLOPs: 0

(_train_tune pid=4727) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=4727) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=4727) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=4727)                                                               train_loss_step:
(_train_tune pid=4727)                                                               0.816
(_train_tune pid=4727)                                                               train_loss_epoch:
(_train_tune pid=4727)                                                               0.816 valid_loss:
(_train_tune pid=4727)                                                               0.126

(_train_tune pid=4939) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=4939) Seed set to 7
(_train_tune pid=4939) GPU available: False, used: False
(_train_tune pid=4939) TPU available: False, using: 0 TPU cores
(_train_tune pid=4939) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=4939) 2026-05-05 12:41:02.377174: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=4939) 2026-05-05 12:41:02.452751: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=4939) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=4939) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=4939) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=4939) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=4939) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=4939) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=4939) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=4939) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=4939) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=4939) Trainable params: 2.7 M
(_train_tune pid=4939) Non-trainable params: 9.6 K
(_train_tune pid=4939) Total params: 2.7 M
(_train_tune pid=4939) Total estimated model params size (MB): 10
(_train_tune pid=4939) Modules in train mode: 31
(_train_tune pid=4939) Modules in eval mode: 0
(_train_tune pid=4939) Total FLOPs: 0

(_train_tune pid=4939) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=4939) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=4939)                                                               train_loss_step:
(_train_tune pid=4939)                                                               0.130
(_train_tune pid=4939)                                                               train_loss_epoch:
(_train_tune pid=4939)                                                               0.130 valid_loss:
(_train_tune pid=4939)                                                               0.176

(_train_tune pid=4939) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=5224) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=5224) Seed set to 3
(_train_tune pid=5224) GPU available: False, used: False
(_train_tune pid=5224) TPU available: False, using: 0 TPU cores
(_train_tune pid=5224) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=5224) 2026-05-05 12:42:01.536313: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=5224) 2026-05-05 12:42:01.613509: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=5224) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=5224) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=5224) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=5224) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=5224) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=5224) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=5224) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=5224) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=5224) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=5224) Trainable params: 2.5 M
(_train_tune pid=5224) Non-trainable params: 3.2 K
(_train_tune pid=5224) Total params: 2.5 M
(_train_tune pid=5224) Total estimated model params size (MB): 9
(_train_tune pid=5224) Modules in train mode: 31
(_train_tune pid=5224) Modules in eval mode: 0
(_train_tune pid=5224) Total FLOPs: 0

(_train_tune pid=5224) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=5224) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=5224)                                                               train_loss_step:
(_train_tune pid=5224)                                                               2.349
(_train_tune pid=5224)                                                               train_loss_epoch:
(_train_tune pid=5224)                                                               2.349 valid_loss:
(_train_tune pid=5224)                                                               0.125

(_train_tune pid=5224) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=5402) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=5402) Seed set to 2
(_train_tune pid=5402) GPU available: False, used: False
(_train_tune pid=5402) TPU available: False, using: 0 TPU cores
(_train_tune pid=5402) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=5402) 2026-05-05 12:42:34.005985: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=5402) 2026-05-05 12:42:34.133067: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=5402) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=5402) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=5402) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=5402) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=5402) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=5402) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=5402) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=5402) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=5402) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=5402) Trainable params: 2.6 M
(_train_tune pid=5402) Non-trainable params: 6.4 K
(_train_tune pid=5402) Total params: 2.6 M
(_train_tune pid=5402) Total estimated model params size (MB): 10
(_train_tune pid=5402) Modules in train mode: 31
(_train_tune pid=5402) Modules in eval mode: 0
(_train_tune pid=5402) Total FLOPs: 0

(_train_tune pid=5402) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=5402) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=5402) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=5402)                                                               train_loss_step:
(_train_tune pid=5402)                                                               1.967
(_train_tune pid=5402)                                                               train_loss_epoch:
(_train_tune pid=5402)                                                               1.967 valid_loss:
(_train_tune pid=5402)                                                               0.122

(_train_tune pid=5716) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=5716) Seed set to 5
(_train_tune pid=5716) GPU available: False, used: False
(_train_tune pid=5716) TPU available: False, using: 0 TPU cores
(_train_tune pid=5716) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=5716) 2026-05-05 12:43:38.692324: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=5716) 2026-05-05 12:43:38.771134: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=5716) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=5716) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=5716) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=5716) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=5716) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=5716) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=5716) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=5716) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=5716) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=5716) Trainable params: 2.5 M
(_train_tune pid=5716) Non-trainable params: 3.2 K
(_train_tune pid=5716) Total params: 2.5 M
(_train_tune pid=5716) Total estimated model params size (MB): 9
(_train_tune pid=5716) Modules in train mode: 31
(_train_tune pid=5716) Modules in eval mode: 0
(_train_tune pid=5716) Total FLOPs: 0

(_train_tune pid=5716) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=5716) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=5716)                                                               train_loss_step:
(_train_tune pid=5716)                                                               3.652
(_train_tune pid=5716)                                                               train_loss_epoch:
(_train_tune pid=5716)                                                               3.652 valid_loss:
(_train_tune pid=5716)                                                               3.990

(_train_tune pid=5716) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=5894) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=5894) Seed set to 5
(_train_tune pid=5894) GPU available: False, used: False
(_train_tune pid=5894) TPU available: False, using: 0 TPU cores
(_train_tune pid=5894) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=5894) 2026-05-05 12:44:11.005512: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=5894) 2026-05-05 12:44:11.136978: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=5894) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=5894) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=5894) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=5894) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=5894) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=5894) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=5894) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=5894) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=5894) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=5894) Trainable params: 2.7 M
(_train_tune pid=5894) Non-trainable params: 9.6 K
(_train_tune pid=5894) Total params: 2.7 M
(_train_tune pid=5894) Total estimated model params size (MB): 10
(_train_tune pid=5894) Modules in train mode: 31
(_train_tune pid=5894) Modules in eval mode: 0
(_train_tune pid=5894) Total FLOPs: 0

(_train_tune pid=5894) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=5894) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=5894)                                                               train_loss_step:
(_train_tune pid=5894)                                                               28963958784.000
(_train_tune pid=5894)                                                               train_loss_epoch:
(_train_tune pid=5894)                                                               28963958784.000
(_train_tune pid=5894)                                                               valid_loss:
(_train_tune pid=5894)                                                               29561239552.000

(_train_tune pid=5894) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=6118) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6118) Seed set to 5
(_train_tune pid=6118) GPU available: False, used: False
(_train_tune pid=6118) TPU available: False, using: 0 TPU cores
(_train_tune pid=6118) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=6118) 2026-05-05 12:44:55.571204: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=6118) 2026-05-05 12:44:55.652064: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=6118) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=6118) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=6118) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=6118) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=6118) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=6118) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=6118) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=6118) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=6118) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=6118) Trainable params: 2.6 M
(_train_tune pid=6118) Non-trainable params: 4.8 K
(_train_tune pid=6118) Total params: 2.6 M
(_train_tune pid=6118) Total estimated model params size (MB): 10
(_train_tune pid=6118) Modules in train mode: 31
(_train_tune pid=6118) Modules in eval mode: 0
(_train_tune pid=6118) Total FLOPs: 0

(_train_tune pid=6118) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=6118) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=6118) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=6118)                                                               train_loss_step:
(_train_tune pid=6118)                                                               0.115
(_train_tune pid=6118)                                                               train_loss_epoch:
(_train_tune pid=6118)                                                               0.115 valid_loss:
(_train_tune pid=6118)                                                               0.134

(_train_tune pid=6328) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6328) Seed set to 6
(_train_tune pid=6328) GPU available: False, used: False
(_train_tune pid=6328) TPU available: False, using: 0 TPU cores
(_train_tune pid=6328) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=6328) 2026-05-05 12:45:35.444763: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=6328) 2026-05-05 12:45:35.570965: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=6328) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=6328) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=6328) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=6328) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=6328) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=6328) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=6328) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=6328) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=6328) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=6328) Trainable params: 2.7 M
(_train_tune pid=6328) Non-trainable params: 8.0 K
(_train_tune pid=6328) Total params: 2.7 M
(_train_tune pid=6328) Total estimated model params size (MB): 10
(_train_tune pid=6328) Modules in train mode: 31
(_train_tune pid=6328) Modules in eval mode: 0
(_train_tune pid=6328) Total FLOPs: 0

(_train_tune pid=6328) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=6328) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=6328) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=6328)                                                               train_loss_step:
(_train_tune pid=6328)                                                               1.709
(_train_tune pid=6328)                                                               train_loss_epoch:
(_train_tune pid=6328)                                                               1.709 valid_loss:
(_train_tune pid=6328)                                                               0.185

(_train_tune pid=6511) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6511) Seed set to 5
(_train_tune pid=6511) GPU available: False, used: False
(_train_tune pid=6511) TPU available: False, using: 0 TPU cores
(_train_tune pid=6511) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=6511) 2026-05-05 12:46:08.316048: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=6511) 2026-05-05 12:46:08.393070: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=6511) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=6511) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=6511) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=6511) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=6511) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=6511) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=6511) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=6511) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=6511) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=6511) Trainable params: 2.6 M
(_train_tune pid=6511) Non-trainable params: 4.8 K
(_train_tune pid=6511) Total params: 2.6 M
(_train_tune pid=6511) Total estimated model params size (MB): 10
(_train_tune pid=6511) Modules in train mode: 31
(_train_tune pid=6511) Modules in eval mode: 0
(_train_tune pid=6511) Total FLOPs: 0

(_train_tune pid=6511) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=6511) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=6511)                                                               train_loss_step:
(_train_tune pid=6511)                                                               0.886
(_train_tune pid=6511)                                                               train_loss_epoch:
(_train_tune pid=6511)                                                               0.886 valid_loss:
(_train_tune pid=6511)                                                               0.125

(_train_tune pid=6511) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=6811) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6811) Seed set to 6
(_train_tune pid=6811) GPU available: False, used: False
(_train_tune pid=6811) TPU available: False, using: 0 TPU cores
(_train_tune pid=6811) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=6811) 2026-05-05 12:47:09.855521: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=6811) 2026-05-05 12:47:09.938622: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=6811) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=6811) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=6811) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=6811) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=6811) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=6811) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=6811) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=6811) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=6811) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=6811) Trainable params: 2.7 M
(_train_tune pid=6811) Non-trainable params: 9.6 K
(_train_tune pid=6811) Total params: 2.7 M
(_train_tune pid=6811) Total estimated model params size (MB): 10
(_train_tune pid=6811) Modules in train mode: 31
(_train_tune pid=6811) Modules in eval mode: 0
(_train_tune pid=6811) Total FLOPs: 0

(_train_tune pid=6811) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=6811) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=6811)                                                               train_loss_step:
(_train_tune pid=6811)                                                               0.967
(_train_tune pid=6811)                                                               train_loss_epoch:
(_train_tune pid=6811)                                                               0.967 valid_loss:
(_train_tune pid=6811)                                                               0.169

(_train_tune pid=6811) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=7018) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7018) Seed set to 5
(_train_tune pid=7018) GPU available: False, used: False
(_train_tune pid=7018) TPU available: False, using: 0 TPU cores
(_train_tune pid=7018) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7018) 2026-05-05 12:47:49.899147: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=7018) 2026-05-05 12:47:49.983149: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7018) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7018) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7018) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7018) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7018) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7018) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7018) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7018) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=7018) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7018) Trainable params: 2.7 M
(_train_tune pid=7018) Non-trainable params: 9.6 K
(_train_tune pid=7018) Total params: 2.7 M
(_train_tune pid=7018) Total estimated model params size (MB): 10
(_train_tune pid=7018) Modules in train mode: 31
(_train_tune pid=7018) Modules in eval mode: 0
(_train_tune pid=7018) Total FLOPs: 0

(_train_tune pid=7018) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=7018) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7018)                                                               train_loss_step:
(_train_tune pid=7018)                                                               2.654
(_train_tune pid=7018)                                                               train_loss_epoch:
(_train_tune pid=7018)                                                               2.654 valid_loss:
(_train_tune pid=7018)                                                               0.261

(_train_tune pid=7018) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=7236) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7236) Seed set to 7
(_train_tune pid=7236) GPU available: False, used: False
(_train_tune pid=7236) TPU available: False, using: 0 TPU cores
(_train_tune pid=7236) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7236) 2026-05-05 12:48:32.012010: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=7236) 2026-05-05 12:48:32.088297: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7236) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7236) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7236) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7236) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7236) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7236) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7236) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7236) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=7236) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7236) Trainable params: 2.7 M
(_train_tune pid=7236) Non-trainable params: 8.0 K
(_train_tune pid=7236) Total params: 2.7 M
(_train_tune pid=7236) Total estimated model params size (MB): 10
(_train_tune pid=7236) Modules in train mode: 31
(_train_tune pid=7236) Modules in eval mode: 0
(_train_tune pid=7236) Total FLOPs: 0

(_train_tune pid=7236) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=7236) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=7236) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7236)                                                               train_loss_step:
(_train_tune pid=7236)                                                               0.414
(_train_tune pid=7236)                                                               train_loss_epoch:
(_train_tune pid=7236)                                                               0.414 valid_loss:
(_train_tune pid=7236)                                                               0.178

(_train_tune pid=7397) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7397) Seed set to 2
(_train_tune pid=7397) GPU available: False, used: False
(_train_tune pid=7397) TPU available: False, using: 0 TPU cores
(_train_tune pid=7397) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7397) 2026-05-05 12:49:00.227781: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=7397) 2026-05-05 12:49:00.306680: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7397) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7397) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7397) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7397) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7397) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7397) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7397) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7397) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=7397) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7397) Trainable params: 2.6 M
(_train_tune pid=7397) Non-trainable params: 6.4 K
(_train_tune pid=7397) Total params: 2.6 M
(_train_tune pid=7397) Total estimated model params size (MB): 10
(_train_tune pid=7397) Modules in train mode: 31
(_train_tune pid=7397) Modules in eval mode: 0
(_train_tune pid=7397) Total FLOPs: 0

(_train_tune pid=7397) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=7397) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7397)                                                               train_loss_step:
(_train_tune pid=7397)                                                               2.125
(_train_tune pid=7397)                                                               train_loss_epoch:
(_train_tune pid=7397)                                                               2.125 valid_loss:
(_train_tune pid=7397)                                                               0.126

(_train_tune pid=7397) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=7615) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7615) Seed set to 8
(_train_tune pid=7615) GPU available: False, used: False
(_train_tune pid=7615) TPU available: False, using: 0 TPU cores
(_train_tune pid=7615) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7615) 2026-05-05 12:49:42.211285: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=7615) 2026-05-05 12:49:42.303908: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7615) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7615) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7615) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7615) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7615) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7615) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7615) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7615) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=7615) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7615) Trainable params: 2.6 M
(_train_tune pid=7615) Non-trainable params: 4.8 K
(_train_tune pid=7615) Total params: 2.6 M
(_train_tune pid=7615) Total estimated model params size (MB): 10
(_train_tune pid=7615) Modules in train mode: 31
(_train_tune pid=7615) Modules in eval mode: 0
(_train_tune pid=7615) Total FLOPs: 0

(_train_tune pid=7615) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=7615) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7615)                                                               train_loss_step:
(_train_tune pid=7615)                                                               278.020
(_train_tune pid=7615)                                                               train_loss_epoch:
(_train_tune pid=7615)                                                               278.020
(_train_tune pid=7615)                                                               valid_loss: 45.890

(_train_tune pid=7615) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=7915) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7915) Seed set to 6
(_train_tune pid=7915) GPU available: False, used: False
(_train_tune pid=7915) TPU available: False, using: 0 TPU cores
(_train_tune pid=7915) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7915) 2026-05-05 12:50:45.753737: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=7915) 2026-05-05 12:50:45.829784: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7915) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7915) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7915) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7915) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7915) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7915) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7915) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7915) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=7915) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7915) Trainable params: 2.6 M
(_train_tune pid=7915) Non-trainable params: 4.8 K
(_train_tune pid=7915) Total params: 2.6 M
(_train_tune pid=7915) Total estimated model params size (MB): 10
(_train_tune pid=7915) Modules in train mode: 31
(_train_tune pid=7915) Modules in eval mode: 0
(_train_tune pid=7915) Total FLOPs: 0

(_train_tune pid=7915) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=7915) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=7915) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7915)                                                               train_loss_step:
(_train_tune pid=7915)                                                               0.093
(_train_tune pid=7915)                                                               train_loss_epoch:
(_train_tune pid=7915)                                                               0.093 valid_loss:
(_train_tune pid=7915)                                                               0.170

(_train_tune pid=8183) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8183) Seed set to 2
(_train_tune pid=8183) GPU available: False, used: False
(_train_tune pid=8183) TPU available: False, using: 0 TPU cores
(_train_tune pid=8183) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8183) 2026-05-05 12:51:39.436480: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=8183) 2026-05-05 12:51:39.566800: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8183) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=8183) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8183) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8183) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8183) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8183) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8183) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8183) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=8183) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8183) Trainable params: 2.7 M
(_train_tune pid=8183) Non-trainable params: 8.0 K
(_train_tune pid=8183) Total params: 2.7 M
(_train_tune pid=8183) Total estimated model params size (MB): 10
(_train_tune pid=8183) Modules in train mode: 31
(_train_tune pid=8183) Modules in eval mode: 0
(_train_tune pid=8183) Total FLOPs: 0

(_train_tune pid=8183) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=8183) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8183)                                                               train_loss_step:
(_train_tune pid=8183)                                                               5.428
(_train_tune pid=8183)                                                               train_loss_epoch:
(_train_tune pid=8183)                                                               5.428 valid_loss:
(_train_tune pid=8183)                                                               0.561

(_train_tune pid=8183) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=8364) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8364) Seed set to 2
(_train_tune pid=8364) GPU available: False, used: False
(_train_tune pid=8364) TPU available: False, using: 0 TPU cores
(_train_tune pid=8364) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8364) 2026-05-05 12:52:12.432022: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=8364) 2026-05-05 12:52:12.512974: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8364) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=8364) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8364) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8364) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8364) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8364) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8364) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8364) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=8364) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8364) Trainable params: 2.5 M
(_train_tune pid=8364) Non-trainable params: 3.2 K
(_train_tune pid=8364) Total params: 2.5 M
(_train_tune pid=8364) Total estimated model params size (MB): 9
(_train_tune pid=8364) Modules in train mode: 31
(_train_tune pid=8364) Modules in eval mode: 0
(_train_tune pid=8364) Total FLOPs: 0

(_train_tune pid=8364) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=8364) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=8364) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8364)                                                               train_loss_step:
(_train_tune pid=8364)                                                               104.139
(_train_tune pid=8364)                                                               train_loss_epoch:
(_train_tune pid=8364)                                                               104.139
(_train_tune pid=8364)                                                               valid_loss: 8.218

(_train_tune pid=8653) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8653) Seed set to 6
(_train_tune pid=8653) GPU available: False, used: False
(_train_tune pid=8653) TPU available: False, using: 0 TPU cores
(_train_tune pid=8653) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8653) 2026-05-05 12:53:11.988153: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=8653) 2026-05-05 12:53:12.066361: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8653) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=8653) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8653) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8653) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8653) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8653) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8653) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8653) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=8653) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8653) Trainable params: 2.7 M
(_train_tune pid=8653) Non-trainable params: 9.6 K
(_train_tune pid=8653) Total params: 2.7 M
(_train_tune pid=8653) Total estimated model params size (MB): 10
(_train_tune pid=8653) Modules in train mode: 31
(_train_tune pid=8653) Modules in eval mode: 0
(_train_tune pid=8653) Total FLOPs: 0

(_train_tune pid=8653) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=8653) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8653)                                                               train_loss_step:
(_train_tune pid=8653)                                                               622085.938
(_train_tune pid=8653)                                                               train_loss_epoch:
(_train_tune pid=8653)                                                               622085.938
(_train_tune pid=8653)                                                               valid_loss:
(_train_tune pid=8653)                                                               87880.523

(_train_tune pid=8653) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=8916) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8916) Seed set to 8
(_train_tune pid=8916) GPU available: False, used: False
(_train_tune pid=8916) TPU available: False, using: 0 TPU cores
(_train_tune pid=8916) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8916) 2026-05-05 12:54:05.471361: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
(_train_tune pid=8916) 2026-05-05 12:54:05.548671: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8916) To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=8916) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8916) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8916) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8916) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8916) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8916) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8916) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=8916) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8916) Trainable params: 2.6 M
(_train_tune pid=8916) Non-trainable params: 6.4 K
(_train_tune pid=8916) Total params: 2.6 M
(_train_tune pid=8916) Total estimated model params size (MB): 10
(_train_tune pid=8916) Modules in train mode: 31
(_train_tune pid=8916) Modules in eval mode: 0
(_train_tune pid=8916) Total FLOPs: 0

(_train_tune pid=8916) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
2026-05-05 12:54:45,720	INFO tune.py:1001 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/_train_tune_2026-05-05_12-39-18' in 0.0172s.
INFO:lightning_fabric.utilities.seed:Seed set to 2
(_train_tune pid=8916) `Trainer.fit` stopped: `max_steps=100` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

(_train_tune pid=8916) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8916)                                                               train_loss_step:
(_train_tune pid=8916)                                                               1.695
(_train_tune pid=8916)                                                               train_loss_epoch:
(_train_tune pid=8916)                                                               1.695 valid_loss:
(_train_tune pid=8916)                                                               0.181

┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ loss         │ MAE           │      0 │ eval  │     0 │
│ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
│ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
│ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
└───┴──────────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 2.6 M
Non-trainable params: 6.4 K
Total params: 2.6 M
Total estimated model params size (MB): 10
Modules in train mode: 30
Modules in eval mode: 1
Total FLOPs: 0

Output()

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)`
is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=100` reached.

INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Output()

In [ ]:
# save as parquet just incase
cross_autonb.to_parquet('cross_autonb.parquet', index=False)

In [ ]:
# Evaluate the model
eval_autonbeats = evaluate(
    df=cross_autonb,
    metrics=[bias, mae, rmse, mape],
    models=['AutoNBEATS'])

In [ ]:
# Drop identifiers and average metrics across all series and cutoffs for easier metrics comparison
eval_autonbeats = eval_autonbeats.drop(columns=['cutoff']).groupby(['unique_id', 'metric']).mean().reset_index(inplace=False)
eval_autonbeats

# Save evaluation as parquete
eval_autonbeats.to_parquet('eval_autonbeats_1.parquet', index=False)

In [ ]:
eval_autonbeats.head()

   unique_id metric  AutoNBEATS
0    hotel_0   bias   -0.004609
1    hotel_0    mae    0.161878
2    hotel_0   mape    0.261339
3    hotel_0   rmse    0.195913
4  hotel_105   bias   -0.090817