# Library Imports

In [ ]:
!pip install neuralforecast hyperopt

# Data prep & all of them
!pip install utilsforecast
import pandas as pd
import matplotlib.pyplot as plt
from utilsforecast.plotting import plot_series
from utilsforecast.losses import bias, rmse, mae, mape, bias
from utilsforecast.evaluation import evaluate


from neuralforecast import NeuralForecast
from ray import tune
from neuralforecast.auto import AutoNHITS

Requirement already satisfied: neuralforecast in /usr/local/lib/python3.12/dist-packages (3.1.7)
Requirement already satisfied: hyperopt in /usr/local/lib/python3.12/dist-packages (0.2.7)
Requirement already satisfied: coreforecast>=0.0.6 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (0.0.17)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2025.3.0)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.0.2)
Requirement already satisfied: pandas>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (1.16.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.10.0+cu128)
Requirement already satisfied: tornado>=6.5.5 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (6.5.5)
Requirement already satisfied: pytorch-lightning>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (2.6.1)
Requirement already satisfied: ray>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (2.55.1)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (4.8.0)
Requirement already satisfied: utilsforecast>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from neuralforecast) (0.2.16)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from hyperopt) (1.17.0)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.12/dist-packages (from hyperopt) (3.6.1)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from hyperopt) (4.67.3)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from hyperopt) (3.1.2)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt) (0.10.9.9)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->neuralforecast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->neuralforecast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->neuralforecast) (2026.1)
Requirement already satisfied: PyYAML>5.4 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (6.0.3)
Requirement already satisfied: torchmetrics>0.7.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (1.9.0)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (26.1)
Requirement already satisfied: typing-extensions>4.5.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (4.15.0)
Requirement already satisfied: lightning-utilities>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning>=2.0.0->neuralforecast) (0.15.3)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (8.3.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.29.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (4.26.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (1.1.2)
Requirement already satisfied: protobuf>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (5.29.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2.32.4)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (2.12.3)
Requirement already satisfied: tensorboardX>=1.9 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (2.6.5)
Requirement already satisfied: pyarrow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from ray[train,tune]>=2.2.0->neuralforecast) (18.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->neuralforecast) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.4.0->neuralforecast) (1.5.3)
Requirement already satisfied: narwhals>=2.0 in /usr/local/lib/python3.12/dist-packages (from utilsforecast>=0.2.3->neuralforecast) (2.20.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->neuralforecast) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->neuralforecast) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->neuralforecast) (2.0.49)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->neuralforecast) (1.3.11)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (3.13.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.10.*,!=2.11.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3->ray[train,tune]>=2.2.0->neuralforecast) (0.4.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->neuralforecast) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->neuralforecast) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->neuralforecast) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (0.30.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.2.0->ray[train,tune]>=2.2.0->neuralforecast) (2026.4.22)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=2.0.0->neuralforecast) (1.23.0)
Requirement already satisfied: utilsforecast in /usr/local/lib/python3.12/dist-packages (0.2.16)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (26.1)
Requirement already satisfied: pandas<3.0.0 in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (2.2.2)
Requirement already satisfied: narwhals>=2.0 in /usr/local/lib/python3.12/dist-packages (from utilsforecast) (2.20.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0->utilsforecast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0->utilsforecast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0->utilsforecast) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0->utilsforecast) (1.17.0)

# Data Preparation (this is shortened from first version)

In [ ]:
df_base = pd.read_parquet('/content/sample_hotels-1.parquet')
df_base.head()

,unique_id,ds,holiday_flag,target_day,target_month,target_year,location_type,hotel_type,y,otb_1,...,otb_51,otb_52,otb_53,otb_54,otb_55,otb_56,otb_57,otb_58,otb_59,otb_60
1430,hotel_0,2022-01-01,no,Sat,Jan,2022,NonSuburban,Resorts & Destinations,0.975309,0.679012,...,0.197531,0.197531,0.197531,0.185185,0.160494,0.160494,0.160494,0.160494,0.160494,0.160494
1431,hotel_0,2022-01-02,no,Sun,Jan,2022,NonSuburban,Resorts & Destinations,0.493827,0.308642,...,0.074074,0.074074,0.074074,0.074074,0.074074,0.061728,0.061728,0.061728,0.061728,0.049383
1432,hotel_0,2022-01-03,no,Mon,Jan,2022,NonSuburban,Resorts & Destinations,0.456790,0.358025,...,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691,0.024691
1433,hotel_0,2022-01-04,no,Tue,Jan,2022,NonSuburban,Resorts & Destinations,0.592593,0.419753,...,0.074074,0.074074,0.074074,0.074074,0.061728,0.061728,0.037037,0.037037,0.024691,0.024691
1434,hotel_0,2022-01-05,no,Wed,Jan,2022,NonSuburban,Resorts & Destinations,0.530864,0.407407,...,0.074074,0.074074,0.074074,0.074074,0.074074,0.049383,0.049383,0.024691,0.024691,0.012346

Drop uninformative variable

In [ ]:
df_base = df_base.drop(columns=['target_year'])

Dummies

In [ ]:
 # Convert holiday flag to boolean manually
 df_base['holiday_flag'] = df_base['holiday_flag'].astype('bool')

In [ ]:
cat_cols = [
    'target_day',
    'target_month',
    'location_type',
    'hotel_type'
]

for col in cat_cols:
    df_base[col] = df_base[col].astype('category')

In [ ]:
df_base = pd.get_dummies(df_base, columns=cat_cols, drop_first=True)

Drop Hotels

In [ ]:
hotels_to_drop = ['hotel_28', 'hotel_77']
df_base = df_base[df_base['unique_id'].isin(hotels_to_drop) == False]

In [ ]:
# Verify that the specified hotels have been dropped from the DataFrame
print(f"'hotel_28' in unique_ids: {'hotel_28' in df_base['unique_id'].unique()}")
print(f"'hotel_77' in unique_ids: {'hotel_77' in df_base['unique_id'].unique()}")

'hotel_28' in unique_ids: False
'hotel_77' in unique_ids: False

OTB

In [ ]:
# Drop all OTB values before otb_28 because that information wouldn't actually be available at the time of forecasting
# By only keeping otb_28 and beyond, I ensure the model doesn't "cheat" by looking at data from inside the 28-day period
columns_to_drop = [f'otb_{i}' for i in range(1, 28)]
df_base = df_base.drop(columns=columns_to_drop)
display(df_base.head())

,unique_id,ds,y,otb_28,otb_29,otb_30,otb_31,otb_32,otb_33,otb_34,...,target_month_Jun,target_month_Mar,target_month_May,target_month_Nov,target_month_Oct,target_month_Sep,location_type_NonSuburban,hotel_type_Key Central Business District,hotel_type_Other High Leisure Mix,hotel_type_Resorts & Destinations
1430,hotel_0,2022-01-01,0.975309,0.296296,0.283951,0.296296,0.296296,0.283951,0.259259,0.234568,...,False,False,False,False,False,False,True,False,False,True
1431,hotel_0,2022-01-02,0.493827,0.086420,0.086420,0.086420,0.086420,0.086420,0.086420,0.086420,...,False,False,False,False,False,False,True,False,False,True
1432,hotel_0,2022-01-03,0.456790,0.061728,0.061728,0.061728,0.061728,0.061728,0.061728,0.049383,...,False,False,False,False,False,False,True,False,False,True
1433,hotel_0,2022-01-04,0.592593,0.111111,0.111111,0.111111,0.111111,0.098765,0.098765,0.098765,...,False,False,False,False,False,False,True,False,False,True
1434,hotel_0,2022-01-05,0.530864,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,0.111111,...,False,False,False,False,False,False,True,False,False,True

Test/Train and Pred/No Pred Split

In [ ]:
# cutoff
cutoff = '2023-05-31'

#train/test split
train = df_base[df_base['ds'] <= cutoff]
test = df_base[df_base['ds'] > cutoff]

# full df no pred
df_no_pred = df_base[['unique_id', 'ds', 'y']]

# train
train_base = train[['unique_id', 'ds', 'y']] # Nixtila format dataset
train_ml = train.copy() # full dataset for ML

test_base = test[['unique_id', 'ds', 'y']]
test_ml = test.copy()

# AutoNHITS Cross Validation and Evaluation

In [ ]:
 # Extract the default hyperparameter settings
nhits_config = AutoNHITS.get_default_config(h = 28, backend="ray")

# 1. Set the training steps (100 for now, 1000 for final)
nhits_config["max_steps"] = tune.choice([100])

# Using a range for the random seed during the search phase
# This makes sure the model isn't just "lucky" with its starting weights
nhits_config["random_seed"] = tune.randint(1, 10)

# Testing different kernel sizes to see how the model pools temporal data
# [2,2,2] is for short-term patterns, [16,8,1] looks at longer-term trends
nhits_config["n_pool_kernel_size"] = tune.choice([[2, 2, 2], [16, 8, 1]])

In [ ]:
# Check hyperparameters configuration
nhits_config

{'h': None,
 'n_pool_kernel_size': <ray.tune.search.sample.Categorical at 0x7d68654eb170>,
 'n_freq_downsample': <ray.tune.search.sample.Categorical at 0x7d6865643b60>,
 'learning_rate': <ray.tune.search.sample.Float at 0x7d6865643bf0>,
 'scaler_type': <ray.tune.search.sample.Categorical at 0x7d6865643c50>,
 'max_steps': <ray.tune.search.sample.Categorical at 0x7d68654eb1a0>,
 'batch_size': <ray.tune.search.sample.Categorical at 0x7d6865643d70>,
 'windows_batch_size': <ray.tune.search.sample.Categorical at 0x7d6865643dd0>,
 'loss': None,
 'random_seed': <ray.tune.search.sample.Integer at 0x7d68654eb110>,
 'input_size': <ray.tune.search.sample.Categorical at 0x7d68654d7140>,
 'step_size': <ray.tune.search.sample.Categorical at 0x7d68654eb920>}

In [ ]:
# Define Models
autonh_model = [
    AutoNHITS(
        h = 28,
        config = nhits_config,
        num_samples = 20) ]

In [ ]:
# Create model object
n_hits = NeuralForecast(
    models=autonh_model,
    freq='D')

In [ ]:
# Cross Validation
cross_autonhit = n_hits.cross_validation(
    df = df_base,
    step_size = 28,
    n_windows = 5
)

2026-05-05 11:58:15,456	INFO worker.py:2012 -- Started a local Ray instance.
/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py:2051: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
2026-05-05 11:58:19,279	INFO tune.py:253 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.

+--------------------------------------------------------------------+
| Configuration for experiment     _train_tune_2026-05-05_11-58-05   |
+--------------------------------------------------------------------+
| Search algorithm                 BasicVariantGenerator             |
| Scheduler                        FIFOScheduler                     |
| Number of trials                 20                                |
+--------------------------------------------------------------------+

View detailed results here: /root/ray_results/_train_tune_2026-05-05_11-58-05
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2026-05-05_11-58-05_011602_5680/artifacts/2026-05-05_11-58-19/_train_tune_2026-05-05_11-58-05/driver_artifacts`

(_train_tune pid=6700) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6700) Seed set to 9
(_train_tune pid=6700) GPU available: True (cuda), used: True
(_train_tune pid=6700) TPU available: False, using: 0 TPU cores
(_train_tune pid=6700) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=6700) 2026-05-05 11:58:35.695132: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=6700) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=6700) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=6700) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=6700) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=6700) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=6700) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=6700) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=6700) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=6700) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=6700) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=6700) Trainable params: 2.5 M
(_train_tune pid=6700) Non-trainable params: 0
(_train_tune pid=6700) Total params: 2.5 M
(_train_tune pid=6700) Total estimated model params size (MB): 10
(_train_tune pid=6700) Modules in train mode: 34
(_train_tune pid=6700) Modules in eval mode: 0
(_train_tune pid=6700) Total FLOPs: 0

(_train_tune pid=6700) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=6700) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=6700) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=6700)                                                               train_loss_step:
(_train_tune pid=6700)                                                               583159.688
(_train_tune pid=6700)                                                               train_loss_epoch:
(_train_tune pid=6700)                                                               583159.688
(_train_tune pid=6700)                                                               valid_loss:
(_train_tune pid=6700)                                                               280130.500

(_train_tune pid=6859) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6859) Seed set to 5
(_train_tune pid=6859) GPU available: True (cuda), used: True
(_train_tune pid=6859) TPU available: False, using: 0 TPU cores
(_train_tune pid=6859) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=6859) 2026-05-05 11:58:58.061833: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=6859) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=6859) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=6859) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=6859) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=6859) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=6859) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=6859) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=6859) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=6859) │ 3 │ blocks       │ ModuleList    │  2.4 M │ train │     0 │
(_train_tune pid=6859) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=6859) Trainable params: 2.4 M
(_train_tune pid=6859) Non-trainable params: 0
(_train_tune pid=6859) Total params: 2.4 M
(_train_tune pid=6859) Total estimated model params size (MB): 9
(_train_tune pid=6859) Modules in train mode: 34
(_train_tune pid=6859) Modules in eval mode: 0
(_train_tune pid=6859) Total FLOPs: 0

(_train_tune pid=6859) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=6859) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=6859)                                                               train_loss_step:
(_train_tune pid=6859)                                                               36.670
(_train_tune pid=6859)                                                               train_loss_epoch:
(_train_tune pid=6859)                                                               36.670 valid_loss:
(_train_tune pid=6859)                                                               100.492

(_train_tune pid=6859) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=7000) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7000) Seed set to 8
(_train_tune pid=7000) GPU available: True (cuda), used: True
(_train_tune pid=7000) TPU available: False, using: 0 TPU cores
(_train_tune pid=7000) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7000) 2026-05-05 11:59:19.311639: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7000) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=7000) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=7000) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7000) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7000) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7000) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7000) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7000) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7000) │ 3 │ blocks       │ ModuleList    │  2.4 M │ train │     0 │
(_train_tune pid=7000) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7000) Trainable params: 2.4 M
(_train_tune pid=7000) Non-trainable params: 0
(_train_tune pid=7000) Total params: 2.4 M
(_train_tune pid=7000) Total estimated model params size (MB): 9
(_train_tune pid=7000) Modules in train mode: 34
(_train_tune pid=7000) Modules in eval mode: 0
(_train_tune pid=7000) Total FLOPs: 0

(_train_tune pid=7000) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=7000) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=7000) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7000)                                                               train_loss_step:
(_train_tune pid=7000)                                                               1.188
(_train_tune pid=7000)                                                               train_loss_epoch:
(_train_tune pid=7000)                                                               1.188 valid_loss:
(_train_tune pid=7000)                                                               0.127

(_train_tune pid=7141) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7141) Seed set to 2
(_train_tune pid=7141) GPU available: True (cuda), used: True
(_train_tune pid=7141) TPU available: False, using: 0 TPU cores
(_train_tune pid=7141) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7141) 2026-05-05 11:59:39.695852: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7141) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=7141) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=7141) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7141) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7141) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7141) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7141) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7141) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7141) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=7141) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7141) Trainable params: 2.6 M
(_train_tune pid=7141) Non-trainable params: 0
(_train_tune pid=7141) Total params: 2.6 M
(_train_tune pid=7141) Total estimated model params size (MB): 10
(_train_tune pid=7141) Modules in train mode: 34
(_train_tune pid=7141) Modules in eval mode: 0
(_train_tune pid=7141) Total FLOPs: 0

(_train_tune pid=7141) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=7141) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7141)                                                               train_loss_step:
(_train_tune pid=7141)                                                               2.071
(_train_tune pid=7141)                                                               train_loss_epoch:
(_train_tune pid=7141)                                                               2.071 valid_loss:
(_train_tune pid=7141)                                                               0.125

(_train_tune pid=7141) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=7278) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7278) Seed set to 9
(_train_tune pid=7278) GPU available: True (cuda), used: True
(_train_tune pid=7278) TPU available: False, using: 0 TPU cores
(_train_tune pid=7278) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7278) 2026-05-05 12:00:01.128329: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7278) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7278) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7278) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7278) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7278) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7278) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7278) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7278) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=7278) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7278) Trainable params: 2.6 M
(_train_tune pid=7278) Non-trainable params: 0
(_train_tune pid=7278) Total params: 2.6 M
(_train_tune pid=7278) Total estimated model params size (MB): 10
(_train_tune pid=7278) Modules in train mode: 34
(_train_tune pid=7278) Modules in eval mode: 0
(_train_tune pid=7278) Total FLOPs: 0

(_train_tune pid=7278) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=7278) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=7278) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7278)                                                               train_loss_step:
(_train_tune pid=7278)                                                               0.490
(_train_tune pid=7278)                                                               train_loss_epoch:
(_train_tune pid=7278)                                                               0.490 valid_loss:
(_train_tune pid=7278)                                                               0.186

(_train_tune pid=7278) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=7418) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7418) Seed set to 2
(_train_tune pid=7418) GPU available: True (cuda), used: True
(_train_tune pid=7418) TPU available: False, using: 0 TPU cores
(_train_tune pid=7418) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7418) 2026-05-05 12:00:21.702924: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7418) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7418) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7418) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7418) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7418) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7418) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7418) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7418) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=7418) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7418) Trainable params: 2.5 M
(_train_tune pid=7418) Non-trainable params: 0
(_train_tune pid=7418) Total params: 2.5 M
(_train_tune pid=7418) Total estimated model params size (MB): 10
(_train_tune pid=7418) Modules in train mode: 34
(_train_tune pid=7418) Modules in eval mode: 0
(_train_tune pid=7418) Total FLOPs: 0

(_train_tune pid=7418) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=7418) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=7418) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=7418) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7418)                                                               train_loss_step:
(_train_tune pid=7418)                                                               0.316
(_train_tune pid=7418)                                                               train_loss_epoch:
(_train_tune pid=7418)                                                               0.316 valid_loss:
(_train_tune pid=7418)                                                               0.176

(_train_tune pid=7559) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7559) Seed set to 7
(_train_tune pid=7559) GPU available: True (cuda), used: True
(_train_tune pid=7559) TPU available: False, using: 0 TPU cores
(_train_tune pid=7559) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7559) 2026-05-05 12:00:43.149889: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7559) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7559) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7559) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7559) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7559) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7559) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7559) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7559) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=7559) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7559) Trainable params: 2.5 M
(_train_tune pid=7559) Non-trainable params: 0
(_train_tune pid=7559) Total params: 2.5 M
(_train_tune pid=7559) Total estimated model params size (MB): 10
(_train_tune pid=7559) Modules in train mode: 34
(_train_tune pid=7559) Modules in eval mode: 0
(_train_tune pid=7559) Total FLOPs: 0

(_train_tune pid=7559) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=7559) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=7559) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=7559) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7559)                                                               train_loss_step:
(_train_tune pid=7559)                                                               1.286
(_train_tune pid=7559)                                                               train_loss_epoch:
(_train_tune pid=7559)                                                               1.286 valid_loss:
(_train_tune pid=7559)                                                               0.160

(_train_tune pid=7692) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7692) Seed set to 5
(_train_tune pid=7692) GPU available: True (cuda), used: True
(_train_tune pid=7692) TPU available: False, using: 0 TPU cores
(_train_tune pid=7692) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7692) 2026-05-05 12:01:04.390592: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7692) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=7692) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=7692) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7692) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7692) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7692) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7692) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7692) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7692) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=7692) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7692) Trainable params: 2.5 M
(_train_tune pid=7692) Non-trainable params: 0
(_train_tune pid=7692) Total params: 2.5 M
(_train_tune pid=7692) Total estimated model params size (MB): 10
(_train_tune pid=7692) Modules in train mode: 34
(_train_tune pid=7692) Modules in eval mode: 0
(_train_tune pid=7692) Total FLOPs: 0

(_train_tune pid=7692) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=7692) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=7692) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7692)                                                               train_loss_step:
(_train_tune pid=7692)                                                               0.931
(_train_tune pid=7692)                                                               train_loss_epoch:
(_train_tune pid=7692)                                                               0.931 valid_loss:
(_train_tune pid=7692)                                                               0.130

(_train_tune pid=7836) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7836) Seed set to 3
(_train_tune pid=7836) GPU available: True (cuda), used: True
(_train_tune pid=7836) TPU available: False, using: 0 TPU cores
(_train_tune pid=7836) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7836) 2026-05-05 12:01:25.811828: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7836) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=7836) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=7836) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7836) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7836) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7836) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7836) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7836) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7836) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=7836) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7836) Trainable params: 2.5 M
(_train_tune pid=7836) Non-trainable params: 0
(_train_tune pid=7836) Total params: 2.5 M
(_train_tune pid=7836) Total estimated model params size (MB): 10
(_train_tune pid=7836) Modules in train mode: 34
(_train_tune pid=7836) Modules in eval mode: 0
(_train_tune pid=7836) Total FLOPs: 0

(_train_tune pid=7836) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=7836) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=7836) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7836)                                                               train_loss_step:
(_train_tune pid=7836)                                                               588.213
(_train_tune pid=7836)                                                               train_loss_epoch:
(_train_tune pid=7836)                                                               588.213
(_train_tune pid=7836)                                                               valid_loss:
(_train_tune pid=7836)                                                               291.750

(_train_tune pid=7976) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7976) Seed set to 2
(_train_tune pid=7976) GPU available: True (cuda), used: True
(_train_tune pid=7976) TPU available: False, using: 0 TPU cores
(_train_tune pid=7976) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=7976) 2026-05-05 12:01:47.565986: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=7976) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=7976) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=7976) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=7976) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=7976) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=7976) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=7976) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=7976) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=7976) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=7976) Trainable params: 2.6 M
(_train_tune pid=7976) Non-trainable params: 0
(_train_tune pid=7976) Total params: 2.6 M
(_train_tune pid=7976) Total estimated model params size (MB): 10
(_train_tune pid=7976) Modules in train mode: 34
(_train_tune pid=7976) Modules in eval mode: 0
(_train_tune pid=7976) Total FLOPs: 0

(_train_tune pid=7976) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=7976) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=7976) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=7976)                                                               train_loss_step:
(_train_tune pid=7976)                                                               0.213
(_train_tune pid=7976)                                                               train_loss_epoch:
(_train_tune pid=7976)                                                               0.213 valid_loss:
(_train_tune pid=7976)                                                               0.174

(_train_tune pid=7976) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=8114) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8114) Seed set to 8
(_train_tune pid=8114) GPU available: True (cuda), used: True
(_train_tune pid=8114) TPU available: False, using: 0 TPU cores
(_train_tune pid=8114) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8114) 2026-05-05 12:02:08.115624: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8114) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=8114) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=8114) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8114) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8114) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8114) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8114) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8114) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8114) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=8114) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8114) Trainable params: 2.5 M
(_train_tune pid=8114) Non-trainable params: 0
(_train_tune pid=8114) Total params: 2.5 M
(_train_tune pid=8114) Total estimated model params size (MB): 10
(_train_tune pid=8114) Modules in train mode: 34
(_train_tune pid=8114) Modules in eval mode: 0
(_train_tune pid=8114) Total FLOPs: 0

(_train_tune pid=8114) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=8114) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=8114) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8114)                                                               train_loss_step:
(_train_tune pid=8114)                                                               1.154
(_train_tune pid=8114)                                                               train_loss_epoch:
(_train_tune pid=8114)                                                               1.154 valid_loss:
(_train_tune pid=8114)                                                               0.159

(_train_tune pid=8255) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8255) Seed set to 8
(_train_tune pid=8255) GPU available: True (cuda), used: True
(_train_tune pid=8255) TPU available: False, using: 0 TPU cores
(_train_tune pid=8255) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8255) 2026-05-05 12:02:29.946632: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8255) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=8255) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8255) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8255) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8255) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8255) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8255) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8255) │ 3 │ blocks       │ ModuleList    │  2.5 M │ train │     0 │
(_train_tune pid=8255) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8255) Trainable params: 2.5 M
(_train_tune pid=8255) Non-trainable params: 0
(_train_tune pid=8255) Total params: 2.5 M
(_train_tune pid=8255) Total estimated model params size (MB): 10
(_train_tune pid=8255) Modules in train mode: 34
(_train_tune pid=8255) Modules in eval mode: 0
(_train_tune pid=8255) Total FLOPs: 0

(_train_tune pid=8255) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=8255) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=8255) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=8255) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8255)                                                               train_loss_step:
(_train_tune pid=8255)                                                               26.315
(_train_tune pid=8255)                                                               train_loss_epoch:
(_train_tune pid=8255)                                                               26.315 valid_loss:
(_train_tune pid=8255)                                                               3.326

(_train_tune pid=8399) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8399) Seed set to 7
(_train_tune pid=8399) GPU available: True (cuda), used: True
(_train_tune pid=8399) TPU available: False, using: 0 TPU cores
(_train_tune pid=8399) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8399) 2026-05-05 12:02:51.174178: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8399) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=8399) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=8399) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8399) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8399) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8399) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8399) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8399) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8399) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=8399) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8399) Trainable params: 2.6 M
(_train_tune pid=8399) Non-trainable params: 0
(_train_tune pid=8399) Total params: 2.6 M
(_train_tune pid=8399) Total estimated model params size (MB): 10
(_train_tune pid=8399) Modules in train mode: 34
(_train_tune pid=8399) Modules in eval mode: 0
(_train_tune pid=8399) Total FLOPs: 0

(_train_tune pid=8399) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=8399) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=8399) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8399)                                                               train_loss_step:
(_train_tune pid=8399)                                                               0.784
(_train_tune pid=8399)                                                               train_loss_epoch:
(_train_tune pid=8399)                                                               0.784 valid_loss:
(_train_tune pid=8399)                                                               0.168

(_train_tune pid=8543) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8543) Seed set to 8
(_train_tune pid=8543) GPU available: True (cuda), used: True
(_train_tune pid=8543) TPU available: False, using: 0 TPU cores
(_train_tune pid=8543) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8543) 2026-05-05 12:03:12.665719: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8543) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=8543) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=8543) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8543) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8543) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8543) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8543) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8543) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8543) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=8543) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8543) Trainable params: 2.7 M
(_train_tune pid=8543) Non-trainable params: 0
(_train_tune pid=8543) Total params: 2.7 M
(_train_tune pid=8543) Total estimated model params size (MB): 10
(_train_tune pid=8543) Modules in train mode: 34
(_train_tune pid=8543) Modules in eval mode: 0
(_train_tune pid=8543) Total FLOPs: 0

(_train_tune pid=8543) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=8543) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=8543) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8543)                                                               train_loss_step:
(_train_tune pid=8543)                                                               0.289
(_train_tune pid=8543)                                                               train_loss_epoch:
(_train_tune pid=8543)                                                               0.289 valid_loss:
(_train_tune pid=8543)                                                               0.186

(_train_tune pid=8676) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8676) Seed set to 4
(_train_tune pid=8676) GPU available: True (cuda), used: True
(_train_tune pid=8676) TPU available: False, using: 0 TPU cores
(_train_tune pid=8676) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8676) 2026-05-05 12:03:33.094016: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8676) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=8676) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=8676) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8676) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8676) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8676) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8676) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8676) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8676) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=8676) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8676) Trainable params: 2.6 M
(_train_tune pid=8676) Non-trainable params: 0
(_train_tune pid=8676) Total params: 2.6 M
(_train_tune pid=8676) Total estimated model params size (MB): 10
(_train_tune pid=8676) Modules in train mode: 34
(_train_tune pid=8676) Modules in eval mode: 0
(_train_tune pid=8676) Total FLOPs: 0

(_train_tune pid=8676) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=8676) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8676)                                                               train_loss_step:
(_train_tune pid=8676)                                                               0.382
(_train_tune pid=8676)                                                               train_loss_epoch:
(_train_tune pid=8676)                                                               0.382 valid_loss:
(_train_tune pid=8676)                                                               0.177

(_train_tune pid=8676) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=8816) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8816) Seed set to 8
(_train_tune pid=8816) GPU available: True (cuda), used: True
(_train_tune pid=8816) TPU available: False, using: 0 TPU cores
(_train_tune pid=8816) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8816) 2026-05-05 12:03:53.908248: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8816) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=8816) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=8816) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8816) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8816) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8816) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8816) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8816) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8816) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=8816) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8816) Trainable params: 2.6 M
(_train_tune pid=8816) Non-trainable params: 0
(_train_tune pid=8816) Total params: 2.6 M
(_train_tune pid=8816) Total estimated model params size (MB): 10
(_train_tune pid=8816) Modules in train mode: 34
(_train_tune pid=8816) Modules in eval mode: 0
(_train_tune pid=8816) Total FLOPs: 0

(_train_tune pid=8816) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=8816) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=8816) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8816)                                                               train_loss_step:
(_train_tune pid=8816)                                                               1.600
(_train_tune pid=8816)                                                               train_loss_epoch:
(_train_tune pid=8816)                                                               1.600 valid_loss:
(_train_tune pid=8816)                                                               0.162

(_train_tune pid=8952) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8952) Seed set to 2
(_train_tune pid=8952) GPU available: True (cuda), used: True
(_train_tune pid=8952) TPU available: False, using: 0 TPU cores
(_train_tune pid=8952) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=8952) 2026-05-05 12:04:15.359875: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=8952) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=8952) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=8952) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=8952) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=8952) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=8952) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=8952) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=8952) │ 3 │ blocks       │ ModuleList    │  2.7 M │ train │     0 │
(_train_tune pid=8952) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=8952) Trainable params: 2.7 M
(_train_tune pid=8952) Non-trainable params: 0
(_train_tune pid=8952) Total params: 2.7 M
(_train_tune pid=8952) Total estimated model params size (MB): 10
(_train_tune pid=8952) Modules in train mode: 34
(_train_tune pid=8952) Modules in eval mode: 0
(_train_tune pid=8952) Total FLOPs: 0

(_train_tune pid=8952) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=8952) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

(_train_tune pid=8952) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=8952)                                                               train_loss_step:
(_train_tune pid=8952)                                                               0.180
(_train_tune pid=8952)                                                               train_loss_epoch:
(_train_tune pid=8952)                                                               0.180 valid_loss:
(_train_tune pid=8952)                                                               0.183

(_train_tune pid=8952) `Trainer.fit` stopped: `max_steps=100` reached.
(_train_tune pid=9089) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=9089) Seed set to 4
(_train_tune pid=9089) GPU available: True (cuda), used: True
(_train_tune pid=9089) TPU available: False, using: 0 TPU cores
(_train_tune pid=9089) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=9089) 2026-05-05 12:04:36.177201: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=9089) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=9089) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=9089) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=9089) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=9089) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=9089) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=9089) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=9089) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=9089) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=9089) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=9089) Trainable params: 2.6 M
(_train_tune pid=9089) Non-trainable params: 0
(_train_tune pid=9089) Total params: 2.6 M
(_train_tune pid=9089) Total estimated model params size (MB): 10
(_train_tune pid=9089) Modules in train mode: 34
(_train_tune pid=9089) Modules in eval mode: 0
(_train_tune pid=9089) Total FLOPs: 0

(_train_tune pid=9089) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=9089) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=9089) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=9089)                                                               train_loss_step:
(_train_tune pid=9089)                                                               19.571
(_train_tune pid=9089)                                                               train_loss_epoch:
(_train_tune pid=9089)                                                               19.571 valid_loss:
(_train_tune pid=9089)                                                               2.456

(_train_tune pid=9229) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=9229) Seed set to 1
(_train_tune pid=9229) GPU available: True (cuda), used: True
(_train_tune pid=9229) TPU available: False, using: 0 TPU cores
(_train_tune pid=9229) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=9229) 2026-05-05 12:04:57.589665: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=9229) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

(_train_tune pid=9229) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=9229) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=9229) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=9229) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=9229) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=9229) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=9229) │ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
(_train_tune pid=9229) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=9229) Trainable params: 2.6 M
(_train_tune pid=9229) Non-trainable params: 0
(_train_tune pid=9229) Total params: 2.6 M
(_train_tune pid=9229) Total estimated model params size (MB): 10
(_train_tune pid=9229) Modules in train mode: 34
(_train_tune pid=9229) Modules in eval mode: 0
(_train_tune pid=9229) Total FLOPs: 0

(_train_tune pid=9229) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=9229) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=9229) `Trainer.fit` stopped: `max_steps=100` reached.

(_train_tune pid=9229) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=9229)                                                               train_loss_step:
(_train_tune pid=9229)                                                               2.012
(_train_tune pid=9229)                                                               train_loss_epoch:
(_train_tune pid=9229)                                                               2.012 valid_loss:
(_train_tune pid=9229)                                                               0.137

(_train_tune pid=9367) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=9367) Seed set to 4
(_train_tune pid=9367) GPU available: True (cuda), used: True
(_train_tune pid=9367) TPU available: False, using: 0 TPU cores
(_train_tune pid=9367) 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
(_train_tune pid=9367) 2026-05-05 12:05:17.898921: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
(_train_tune pid=9367) To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(_train_tune pid=9367) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

(_train_tune pid=9367) ┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
(_train_tune pid=9367) ┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
(_train_tune pid=9367) ┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
(_train_tune pid=9367) │ 0 │ loss         │ MAE           │      0 │ train │     0 │
(_train_tune pid=9367) │ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
(_train_tune pid=9367) │ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
(_train_tune pid=9367) │ 3 │ blocks       │ ModuleList    │  2.4 M │ train │     0 │
(_train_tune pid=9367) └───┴──────────────┴───────────────┴────────┴───────┴───────┘
(_train_tune pid=9367) Trainable params: 2.4 M
(_train_tune pid=9367) Non-trainable params: 0
(_train_tune pid=9367) Total params: 2.4 M
(_train_tune pid=9367) Total estimated model params size (MB): 9
(_train_tune pid=9367) Modules in train mode: 34
(_train_tune pid=9367) Modules in eval mode: 0
(_train_tune pid=9367) Total FLOPs: 0

(_train_tune pid=9367) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.
(_train_tune pid=9367) `Trainer.fit` stopped: `max_steps=100` reached.
2026-05-05 12:05:22,740	INFO tune.py:1001 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/_train_tune_2026-05-05_11-58-05' in 0.0273s.
INFO:lightning_fabric.utilities.seed:Seed set to 2
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

(_train_tune pid=9367) Epoch 99/-2 ━━━━━━━━━━━━━━━━━━ 1/1 0:00:00 • 0:00:00 0.00it/s v_num: 0.000
(_train_tune pid=9367)                                                               train_loss_step:
(_train_tune pid=9367)                                                               1.913
(_train_tune pid=9367)                                                               train_loss_epoch:
(_train_tune pid=9367)                                                               1.913 valid_loss:
(_train_tune pid=9367)                                                               0.141

INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

┏━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name         ┃ Type          ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ loss         │ MAE           │      0 │ eval  │     0 │
│ 1 │ padder_train │ ConstantPad1d │      0 │ train │     0 │
│ 2 │ scaler       │ TemporalNorm  │      0 │ train │     0 │
│ 3 │ blocks       │ ModuleList    │  2.6 M │ train │     0 │
└───┴──────────────┴───────────────┴────────┴───────┴───────┘

Trainable params: 2.6 M
Non-trainable params: 0
Total params: 2.6 M
Total estimated model params size (MB): 10
Modules in train mode: 33
Modules in eval mode: 1
Total FLOPs: 0

Output()

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)`
is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=100` reached.

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Output()

In [ ]:
# Evaluate the model
eval_autonhits = evaluate(
    df=cross_autonhit,
    metrics=[bias, mae, rmse, mape],
    models=['AutoNHITS']
)

In [ ]:
# Drop identifiers and average metrics across all series and cutoffs for easier metrics comparison
eval_autonhits = eval_autonhits.drop(columns=['cutoff']).groupby(['unique_id', 'metric']).mean().reset_index(inplace=False)
eval_autonhits

# Save evaluation as parquete
eval_autonhits.to_parquet('eval_autonhits.parquet', index=False)

In [ ]:
eval_autonhits.head()

   unique_id metric  AutoNHITS
0    hotel_0   bias   0.000079
1    hotel_0    mae   0.164236
2    hotel_0   mape   0.267327
3    hotel_0   rmse   0.198349
4  hotel_105   bias  -0.085752